name: Release Peguni Draem'la

on:
  push:
    tags:
      - 'v*.*.*'  # Matches semantic versions like v0.1.0, v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install base-devel (for makepkg)
      run: sudo pacman -Sy --noconfirm base-devel

    - name: Generate .SRCINFO
      run: makepkg --printsrcinfo > .SRCINFO

    - name: Commit .SRCINFO if changed
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .SRCINFO
        git diff --cached --quiet || (git commit -m "Update .SRCINFO for ${{ github.ref_name }}" && git push origin HEAD:master)

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}

    # Optional: Upload any custom assets if you have any
    # - name: Upload source tarball
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./path/to/custom.tar.gz
    #     asset_name: peguni_draem-la-${{ github.ref_name }}.tar.gz
    #     asset_content_type: application/gzip
